### ISSUE TITLE
MHBasic REPL broken

### ISSUE THREAD

**Issue by shakna-israel** [echo-lalia/MicroHydra-Apps#29]
I think the BASIC repl is broken, at least for the Cardputer.

Pressing "GO" is supposed to break, allowing you to process a program.

However, processing that button just outputs "g0". That's a zero, not an O.

I think [this](https://github.com/echo-lalia/MicroHydra-Apps/blob/8aaf0a96d4400df6ab7112c21d5036df22fdf65e/app-source/MHBasic/MHBasic.py#L484) line has become outdated or something.

The aux key is "G0" over in [_keys.py](https://github.com/echo-lalia/MicroHydra/blob/main/devices/CARDPUTER/lib/userinput/_keys.py#L54).

**Comment by echo-lalia** [comment]
Thanks for opening this issue, and sorry for the slow response! You are right about the issue; MHydra 1.x used the name "GO" but that was inaccurate and potentially confusing, so I updated it to "G0" while overhauling it for v2.x

I think this app was released just around that same time, and so this issue slipped in. It's an easy fix, so I'll do that now!
