### ISSUE TITLE
Reduce Wikipedia app sleep time when waiting for connection

### ISSUE THREAD

**Issue by l0wigh** [echo-lalia/MicroHydra-Apps#30]
The Wikipedia app feels like it's broken since it uses a `time.sleep(100)` instead of a `time.sleep_ms(100)`

**Comment by echo-lalia** [comment]
🤦‍♂️ thank you for pointing this out. I noticed the connection time was slow, but just assumed it was some opaque connection stability problem that I'd investigate later.

I'll fix this ASAP
